// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uihgqdkjrfphbwpfoils.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaGdxZGtqcmZwaGJ3cGZvaWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODQ3NjAsImV4cCI6MjA2OTU2MDc2MH0.jANe3quDOxIsZzN8fIFUqoWx23szd_I2L5f03k8cqPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});